"""empty message

Revision ID: 4f3eeede9f3f
Revises: fc63dc5d73ce
Create Date: 2025-04-08 23:59:42.111096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3eeede9f3f'
down_revision = 'fc63dc5d73ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
