"""empty message

Revision ID: b28630fe6f5c
Revises: 0527b950c326
Create Date: 2025-04-16 02:05:48.075273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28630fe6f5c'
down_revision = '0527b950c326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
