"""empty message

Revision ID: d4c2237bd475
Revises: e543a917dea6
Create Date: 2025-04-02 17:00:18.895632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c2237bd475'
down_revision = 'e543a917dea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_duration', sa.Integer(), nullable=False))
        batch_op.drop_column('vip_expiration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_expiration_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('vip_duration')

    # ### end Alembic commands ###
