"""empty message

Revision ID: f5727975bfec
Revises: d4c2237bd475
Create Date: 2025-04-08 22:53:03.773502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5727975bfec'
down_revision = 'd4c2237bd475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
