"""empty message

Revision ID: fc63dc5d73ce
Revises: f5727975bfec
Create Date: 2025-04-08 23:37:07.479474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc63dc5d73ce'
down_revision = 'f5727975bfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.String(), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=False))
        batch_op.drop_column('item')

    # ### end Alembic commands ###
